-- PostgreSQL 16 reference schema, v1.1. Run ONLY in a new empty test database.
-- Not a Laravel migration or an installation against a live Supabase project.
-- No DROP/TRUNCATE. Existing namespace causes failure rather than overwriting data.
BEGIN;
CREATE SCHEMA recruitment;
SET search_path TO recruitment, pg_catalog;

CREATE TABLE users (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name varchar(160) NOT NULL,
 email varchar(254) NOT NULL CHECK(email = lower(btrim(email)) AND length(email)>3),
 password varchar(255) NOT NULL,
 remember_token varchar(100), email_verified_at timestamptz, disabled_at timestamptz,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 UNIQUE(email)
);
CREATE TABLE org_units (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 parent_id bigint REFERENCES org_units(id) ON DELETE RESTRICT,
 code varchar(40) NOT NULL UNIQUE, name varchar(160) NOT NULL, archived_at timestamptz,
 CHECK(parent_id IS NULL OR parent_id <> id)
);
-- Role attached to scope, not the Cartesian product of global roles and units.
CREATE TABLE staff_assignments (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id bigint NOT NULL REFERENCES users ON DELETE RESTRICT,
 role_code varchar(16) NOT NULL CHECK(role_code IN ('admin','manager','sm')),
 org_unit_id bigint REFERENCES org_units ON DELETE RESTRICT,
 valid_from timestamptz NOT NULL DEFAULT now(), valid_to timestamptz,
 CHECK(valid_to IS NULL OR valid_to > valid_from),
 CHECK((role_code='admin' AND org_unit_id IS NULL) OR (role_code IN ('manager','sm') AND org_unit_id IS NOT NULL)),
 UNIQUE(id,user_id,role_code,org_unit_id)
);
CREATE UNIQUE INDEX staff_one_current ON staff_assignments(user_id,role_code,org_unit_id) NULLS NOT DISTINCT WHERE valid_to IS NULL;
CREATE TABLE institutions (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name varchar(200) NOT NULL, institution_type varchar(40) NOT NULL, archived_at timestamptz
);
CREATE TABLE applicant_profiles (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id bigint NOT NULL UNIQUE REFERENCES users ON DELETE RESTRICT,
 phone varchar(32), created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(id,user_id)
);
CREATE TABLE applicant_educations (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 applicant_profile_id bigint NOT NULL REFERENCES applicant_profiles ON DELETE RESTRICT,
 institution_id bigint NOT NULL REFERENCES institutions ON DELETE RESTRICT,
 education_level varchar(40) NOT NULL, major varchar(160) NOT NULL,
 is_active boolean NOT NULL DEFAULT true,
 grade numeric(6,2), grade_scale numeric(6,2),
 CHECK((grade IS NULL AND grade_scale IS NULL) OR (grade IS NOT NULL AND grade_scale IS NOT NULL AND grade>=0 AND grade_scale>0 AND grade<=grade_scale))
);
CREATE TABLE internship_programs (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, code varchar(40) NOT NULL UNIQUE, name varchar(160) NOT NULL, archived_at timestamptz);
CREATE TABLE internship_positions (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, code varchar(40) NOT NULL UNIQUE, title varchar(160) NOT NULL, description text NOT NULL DEFAULT '', archived_at timestamptz);
CREATE TABLE recruitment_periods (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 code varchar(40) NOT NULL UNIQUE, title varchar(160) NOT NULL,
 opens_at timestamptz NOT NULL, closes_at timestamptz NOT NULL, CHECK(opens_at<closes_at)
);
CREATE TABLE document_types (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, code varchar(40) NOT NULL UNIQUE, label varchar(160) NOT NULL, archived_at timestamptz);
CREATE TABLE internship_requests (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 requester_id bigint NOT NULL REFERENCES users ON DELETE RESTRICT,
 org_unit_id bigint NOT NULL REFERENCES org_units ON DELETE RESTRICT,
 position_id bigint NOT NULL REFERENCES internship_positions ON DELETE RESTRICT,
 period_id bigint NOT NULL REFERENCES recruitment_periods ON DELETE RESTRICT,
 requested_count integer NOT NULL CHECK(requested_count>0),
 criteria text NOT NULL DEFAULT '', duties text NOT NULL DEFAULT '',
 status varchar(24) NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','submitted','processing','fulfilled','cancelled')),
 created_at timestamptz NOT NULL DEFAULT now(),
 UNIQUE(id,org_unit_id,position_id,period_id)
);
CREATE TABLE vacancies (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 request_id bigint NOT NULL, org_unit_id bigint NOT NULL, position_id bigint NOT NULL, period_id bigint NOT NULL,
 program_id bigint NOT NULL REFERENCES internship_programs ON DELETE RESTRICT,
 slug varchar(200) NOT NULL UNIQUE, quota integer NOT NULL CHECK(quota>0),
 starts_on date NOT NULL, ends_on date NOT NULL CHECK(ends_on>=starts_on),
 description text NOT NULL DEFAULT '',
 status varchar(16) NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','published','closed','archived')),
 published_at timestamptz,
 CHECK((status='draft' AND published_at IS NULL) OR (status<>'draft' AND published_at IS NOT NULL)),
 FOREIGN KEY(request_id,org_unit_id,position_id,period_id) REFERENCES internship_requests(id,org_unit_id,position_id,period_id) ON DELETE RESTRICT,
 UNIQUE(id,period_id), UNIQUE(id,org_unit_id)
);
CREATE TABLE vacancy_requirements (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 vacancy_id bigint NOT NULL REFERENCES vacancies ON DELETE RESTRICT,
 label varchar(160) NOT NULL, description text NOT NULL DEFAULT ''
);
CREATE TABLE vacancy_document_requirements (
 vacancy_id bigint NOT NULL REFERENCES vacancies ON DELETE RESTRICT,
 document_type_id bigint NOT NULL REFERENCES document_types ON DELETE RESTRICT,
 required boolean NOT NULL DEFAULT true,
 source_allowed varchar(16) NOT NULL CHECK(source_allowed IN ('individual','group','either')),
 PRIMARY KEY(vacancy_id,document_type_id)
);
CREATE TABLE application_groups (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 institution_id bigint NOT NULL REFERENCES institutions ON DELETE RESTRICT,
 period_id bigint NOT NULL REFERENCES recruitment_periods ON DELETE RESTRICT,
 coordinator_user_id bigint NOT NULL REFERENCES users ON DELETE RESTRICT,
 title varchar(200) NOT NULL,
 status varchar(16) NOT NULL DEFAULT 'active' CHECK(status IN ('active','closed')),
 UNIQUE(id,period_id)
);
CREATE TABLE application_group_members (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 group_id bigint NOT NULL, period_id bigint NOT NULL,
 invited_email varchar(254) NOT NULL CHECK(invited_email=lower(btrim(invited_email))),
 invited_name varchar(160) NOT NULL,
 claimed_user_id bigint REFERENCES users ON DELETE RESTRICT,
 confirmed_at timestamptz,
 status varchar(16) NOT NULL DEFAULT 'invited' CHECK(status IN ('invited','confirmed','revoked')),
 CHECK((claimed_user_id IS NULL)=(confirmed_at IS NULL)),
 CHECK(status<>'confirmed' OR claimed_user_id IS NOT NULL),
 FOREIGN KEY(group_id,period_id) REFERENCES application_groups(id,period_id) ON DELETE RESTRICT,
 UNIQUE(group_id,invited_email), UNIQUE(group_id,claimed_user_id),
 UNIQUE(id,claimed_user_id,period_id)
);
CREATE TABLE group_invitations (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 member_id bigint NOT NULL REFERENCES application_group_members ON DELETE RESTRICT,
 token_hash varchar(64) NOT NULL UNIQUE CHECK(token_hash ~ '^[0-9a-f]{64}$'),
 created_at timestamptz NOT NULL DEFAULT now(), expires_at timestamptz NOT NULL,
 used_at timestamptz, revoked_at timestamptz,
 CHECK(expires_at>created_at), CHECK(NOT(used_at IS NOT NULL AND revoked_at IS NOT NULL))
);
CREATE UNIQUE INDEX one_open_invitation ON group_invitations(member_id) WHERE used_at IS NULL AND revoked_at IS NULL;
CREATE TABLE stored_files (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 disk varchar(40) NOT NULL, object_key varchar(500) NOT NULL,
 uploader_id bigint NOT NULL REFERENCES users ON DELETE RESTRICT,
 mime varchar(100) NOT NULL CHECK(mime='application/pdf'),
 byte_size bigint NOT NULL CHECK(byte_size>0 AND byte_size<=5242880),
 sha256 varchar(64) NOT NULL CHECK(sha256 ~ '^[0-9a-f]{64}$'),
 scan_status varchar(16) NOT NULL DEFAULT 'pending' CHECK(scan_status IN ('pending','clean','rejected')),
 created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(disk,object_key)
);
CREATE TABLE group_documents (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 group_id bigint NOT NULL REFERENCES application_groups ON DELETE RESTRICT,
 document_type_id bigint NOT NULL REFERENCES document_types ON DELETE RESTRICT,
 version_no integer NOT NULL CHECK(version_no>0),
 stored_file_id bigint NOT NULL REFERENCES stored_files ON DELETE RESTRICT,
 UNIQUE(group_id,document_type_id,version_no), UNIQUE(id,stored_file_id,document_type_id)
);
CREATE TABLE applications (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 public_reference varchar(50) NOT NULL UNIQUE,
 applicant_profile_id bigint NOT NULL, applicant_user_id bigint NOT NULL,
 vacancy_id bigint NOT NULL, period_id bigint NOT NULL,
 group_member_id bigint UNIQUE,
 stage varchar(32) NOT NULL DEFAULT 'draft' CHECK(stage IN ('draft','submitted','administrative_review','needs_revision','manager_review','sm_review','decided','withdrawn')),
 submitted_at timestamptz, withdrawn_at timestamptz, current_submission_id bigint,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 CHECK((stage='draft' AND submitted_at IS NULL AND current_submission_id IS NULL) OR (stage<>'draft' AND submitted_at IS NOT NULL AND current_submission_id IS NOT NULL)),
 CHECK((stage='withdrawn')=(withdrawn_at IS NOT NULL)),
 FOREIGN KEY(applicant_profile_id,applicant_user_id) REFERENCES applicant_profiles(id,user_id) ON DELETE RESTRICT,
 FOREIGN KEY(vacancy_id,period_id) REFERENCES vacancies(id,period_id) ON DELETE RESTRICT,
 FOREIGN KEY(group_member_id,applicant_user_id,period_id) REFERENCES application_group_members(id,claimed_user_id,period_id) ON DELETE RESTRICT,
 UNIQUE(applicant_profile_id,vacancy_id), UNIQUE(id,vacancy_id), UNIQUE(id,applicant_user_id)
);
-- Draft mutable, history immutable. JSON is draft/snapshot only, not all relational data.
CREATE TABLE application_drafts (
 application_id bigint PRIMARY KEY REFERENCES applications ON DELETE RESTRICT,
 payload jsonb NOT NULL DEFAULT '{}' CHECK(jsonb_typeof(payload)='object'),
 lock_version integer NOT NULL DEFAULT 0 CHECK(lock_version>=0), updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE application_draft_documents (
 application_id bigint NOT NULL REFERENCES application_drafts(application_id) ON DELETE RESTRICT,
 document_type_id bigint NOT NULL REFERENCES document_types ON DELETE RESTRICT,
 stored_file_id bigint NOT NULL REFERENCES stored_files ON DELETE RESTRICT,
 source_group_document_id bigint,
 PRIMARY KEY(application_id,document_type_id),
 FOREIGN KEY(source_group_document_id,stored_file_id,document_type_id) REFERENCES group_documents(id,stored_file_id,document_type_id) ON DELETE RESTRICT
);
CREATE TABLE application_submissions (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 application_id bigint NOT NULL REFERENCES applications ON DELETE RESTRICT,
 version_no integer NOT NULL CHECK(version_no>0),
 profile_snapshot jsonb NOT NULL CHECK(jsonb_typeof(profile_snapshot)='object'),
 education_snapshot jsonb NOT NULL CHECK(jsonb_typeof(education_snapshot)='array'),
 vacancy_snapshot jsonb NOT NULL CHECK(jsonb_typeof(vacancy_snapshot)='object'),
 submitted_by bigint NOT NULL, submitted_at timestamptz NOT NULL DEFAULT now(),
 FOREIGN KEY(application_id,submitted_by) REFERENCES applications(id,applicant_user_id) ON DELETE RESTRICT,
 UNIQUE(application_id,version_no), UNIQUE(application_id,id)
);
ALTER TABLE applications ADD CONSTRAINT current_submission_owned FOREIGN KEY(id,current_submission_id) REFERENCES application_submissions(application_id,id) ON DELETE RESTRICT;
CREATE TABLE application_documents (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 submission_id bigint NOT NULL REFERENCES application_submissions ON DELETE RESTRICT,
 document_type_id bigint NOT NULL REFERENCES document_types ON DELETE RESTRICT,
 stored_file_id bigint NOT NULL REFERENCES stored_files ON DELETE RESTRICT,
 source_group_document_id bigint,
 UNIQUE(submission_id,document_type_id),
 FOREIGN KEY(source_group_document_id,stored_file_id,document_type_id) REFERENCES group_documents(id,stored_file_id,document_type_id) ON DELETE RESTRICT
);
CREATE TABLE application_revision_requests (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 application_id bigint NOT NULL REFERENCES applications ON DELETE RESTRICT,
 requested_by bigint NOT NULL REFERENCES users ON DELETE RESTRICT,
 fields_requested jsonb NOT NULL CHECK(jsonb_typeof(fields_requested)='array'),
 reason text NOT NULL CHECK(length(btrim(reason))>0),
 created_at timestamptz NOT NULL DEFAULT now(), due_at timestamptz NOT NULL,
 status varchar(16) NOT NULL DEFAULT 'open' CHECK(status IN ('open','fulfilled','cancelled')),
 completed_submission_id bigint, completed_at timestamptz, cancelled_at timestamptz,
 CHECK(due_at>created_at),
 CHECK((status='fulfilled' AND completed_submission_id IS NOT NULL AND completed_at IS NOT NULL AND cancelled_at IS NULL)
 OR (status='open' AND completed_submission_id IS NULL AND completed_at IS NULL AND cancelled_at IS NULL)
 OR (status='cancelled' AND completed_submission_id IS NULL AND completed_at IS NULL AND cancelled_at IS NOT NULL)),
 FOREIGN KEY(application_id,completed_submission_id) REFERENCES application_submissions(application_id,id) ON DELETE RESTRICT
);
CREATE UNIQUE INDEX one_open_revision ON application_revision_requests(application_id) WHERE status='open';
CREATE TABLE application_reviews (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 application_id bigint NOT NULL, vacancy_id bigint NOT NULL, org_unit_id bigint NOT NULL,
 stage varchar(16) NOT NULL CHECK(stage IN ('manager','sm')),
 assignee_id bigint NOT NULL, staff_assignment_id bigint NOT NULL,
 revision_no integer NOT NULL DEFAULT 1 CHECK(revision_no>0),
 status varchar(16) NOT NULL CHECK(status IN ('blocked','pending','completed','superseded','cancelled')),
 outcome varchar(24), note_internal text, based_on_submission_id bigint NOT NULL,
 assigned_by bigint NOT NULL REFERENCES users ON DELETE RESTRICT,
 acted_at timestamptz, supersedes_id bigint, created_at timestamptz NOT NULL DEFAULT now(),
 CHECK((status='completed' AND outcome IS NOT NULL AND acted_at IS NOT NULL AND note_internal IS NOT NULL AND length(btrim(note_internal))>0)
 OR (status<>'completed' AND outcome IS NULL AND acted_at IS NULL)),
 CHECK(outcome IS NULL OR (stage='manager' AND outcome IN ('recommended','not_recommended')) OR (stage='sm' AND outcome IN ('accepted','rejected'))),
 CHECK(supersedes_id IS NULL OR supersedes_id<>id),
 FOREIGN KEY(application_id,vacancy_id) REFERENCES applications(id,vacancy_id) ON DELETE RESTRICT,
 FOREIGN KEY(vacancy_id,org_unit_id) REFERENCES vacancies(id,org_unit_id) ON DELETE RESTRICT,
 FOREIGN KEY(staff_assignment_id,assignee_id,stage,org_unit_id) REFERENCES staff_assignments(id,user_id,role_code,org_unit_id) ON DELETE RESTRICT,
 FOREIGN KEY(application_id,based_on_submission_id) REFERENCES application_submissions(application_id,id) ON DELETE RESTRICT,
 UNIQUE(application_id,stage,revision_no), UNIQUE(application_id,stage,id), UNIQUE(application_id,id,stage,status)
);
ALTER TABLE application_reviews ADD CONSTRAINT supersedes_same_stage FOREIGN KEY(application_id,stage,supersedes_id) REFERENCES application_reviews(application_id,stage,id) ON DELETE RESTRICT;
CREATE UNIQUE INDEX one_effective_review ON application_reviews(application_id,stage) WHERE status IN ('blocked','pending','completed');
CREATE TABLE application_publications (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 application_id bigint NOT NULL UNIQUE REFERENCES applications ON DELETE RESTRICT,
 final_review_id bigint NOT NULL UNIQUE,
 final_stage varchar(16) NOT NULL DEFAULT 'sm' CHECK(final_stage='sm'),
 final_status varchar(16) NOT NULL DEFAULT 'completed' CHECK(final_status='completed'),
 published_by bigint NOT NULL REFERENCES users ON DELETE RESTRICT,
 published_at timestamptz NOT NULL DEFAULT now(), public_message text NOT NULL DEFAULT '',
 FOREIGN KEY(application_id,final_review_id,final_stage,final_status) REFERENCES application_reviews(application_id,id,stage,status) ON DELETE RESTRICT
);
CREATE TABLE application_events (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 application_id bigint NOT NULL REFERENCES applications ON DELETE RESTRICT,
 actor_id bigint REFERENCES users ON DELETE RESTRICT, event_type varchar(80) NOT NULL,
 metadata jsonb NOT NULL DEFAULT '{}' CHECK(jsonb_typeof(metadata)='object'), occurred_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE audit_events (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 resource_type varchar(80) NOT NULL, resource_id bigint NOT NULL,
 actor_id bigint REFERENCES users ON DELETE RESTRICT, event_type varchar(80) NOT NULL,
 metadata jsonb NOT NULL DEFAULT '{}' CHECK(jsonb_typeof(metadata)='object'), occurred_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE outbox_events (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 event_key varchar(200) NOT NULL UNIQUE, event_type varchar(80) NOT NULL,
 payload jsonb NOT NULL DEFAULT '{}' CHECK(jsonb_typeof(payload)='object'),
 available_at timestamptz NOT NULL DEFAULT now(), lease_until timestamptz, processed_at timestamptz,
 attempts integer NOT NULL DEFAULT 0 CHECK(attempts>=0), created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE notification_deliveries (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 outbox_id bigint NOT NULL REFERENCES outbox_events ON DELETE RESTRICT,
 recipient_user_id bigint REFERENCES users ON DELETE RESTRICT,
 invitation_id bigint REFERENCES group_invitations ON DELETE RESTRICT,
 channel varchar(16) NOT NULL CHECK(channel IN ('email','in_app')),
 recipient_key varchar(300) NOT NULL,
 email_snapshot varchar(254),
 status varchar(16) NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','sending','sent','failed','cancelled')),
 attempts integer NOT NULL DEFAULT 0 CHECK(attempts>=0), provider_reference varchar(200), sent_at timestamptz,
 CHECK((channel='email' AND email_snapshot IS NOT NULL AND email_snapshot=lower(btrim(email_snapshot)) AND recipient_key='email:'||email_snapshot)
 OR (channel='in_app' AND recipient_user_id IS NOT NULL AND email_snapshot IS NULL AND recipient_key='user:'||recipient_user_id::text)),
 CHECK(status<>'sent' OR sent_at IS NOT NULL),
 UNIQUE(outbox_id,channel,recipient_key)
);
CREATE TABLE delivery_secrets (
 delivery_id bigint PRIMARY KEY REFERENCES notification_deliveries ON DELETE RESTRICT,
 ciphertext bytea NOT NULL, key_version varchar(40) NOT NULL,
 expires_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), CHECK(expires_at>created_at)
);

CREATE INDEX application_inbox ON applications(vacancy_id,stage);
CREATE INDEX application_history ON applications(applicant_profile_id,submitted_at);
CREATE INDEX reviewer_inbox ON application_reviews(assignee_id,status,stage);
CREATE INDEX event_history ON application_events(application_id,occurred_at);
CREATE INDEX outbox_due ON outbox_events(available_at) WHERE processed_at IS NULL;
CREATE INDEX pending_deliveries ON notification_deliveries(status) WHERE status IN ('pending','failed');
CREATE INDEX draft_file_refs ON application_draft_documents(stored_file_id);
CREATE INDEX submission_file_refs ON application_documents(stored_file_id);
CREATE INDEX group_file_refs ON group_documents(stored_file_id);
CREATE INDEX vacancy_request_idx ON vacancies(request_id);
CREATE INDEX member_user_idx ON application_group_members(claimed_user_id);

-- Database immutability protects accidental UPDATE/DELETE, not privileged owners disabling triggers.
CREATE FUNCTION deny_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN RAISE EXCEPTION 'immutable table: %',TG_TABLE_NAME USING ERRCODE='23514'; END $$;
CREATE TRIGGER immutable_submission BEFORE UPDATE OR DELETE ON application_submissions FOR EACH ROW EXECUTE FUNCTION deny_mutation();
CREATE TRIGGER immutable_submission_document BEFORE UPDATE OR DELETE ON application_documents FOR EACH ROW EXECUTE FUNCTION deny_mutation();
CREATE TRIGGER immutable_group_document BEFORE UPDATE OR DELETE ON group_documents FOR EACH ROW EXECUTE FUNCTION deny_mutation();
CREATE TRIGGER immutable_publication BEFORE UPDATE OR DELETE ON application_publications FOR EACH ROW EXECUTE FUNCTION deny_mutation();
CREATE TRIGGER immutable_application_event BEFORE UPDATE OR DELETE ON application_events FOR EACH ROW EXECUTE FUNCTION deny_mutation();
CREATE TRIGGER immutable_audit_event BEFORE UPDATE OR DELETE ON audit_events FOR EACH ROW EXECUTE FUNCTION deny_mutation();
CREATE FUNCTION freeze_completed_review() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF OLD.status='completed' THEN RAISE EXCEPTION 'completed review immutable' USING ERRCODE='23514'; END IF;
 IF TG_OP='DELETE' THEN RETURN OLD; END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER freeze_review BEFORE UPDATE OR DELETE ON application_reviews FOR EACH ROW EXECUTE FUNCTION freeze_completed_review();

CREATE FUNCTION has_staff_scope(p_user bigint,p_role text,p_unit bigint) RETURNS boolean
LANGUAGE sql STABLE SET search_path TO recruitment,pg_catalog AS $$
 SELECT EXISTS(SELECT 1 FROM staff_assignments s JOIN users u ON u.id=s.user_id
 WHERE s.user_id=p_user AND s.role_code=p_role AND s.org_unit_id IS NOT DISTINCT FROM p_unit
 AND s.valid_from<=CURRENT_TIMESTAMP AND (s.valid_to IS NULL OR CURRENT_TIMESTAMP<s.valid_to) AND u.disabled_at IS NULL)
$$;

-- Reference command functions: actor comes from authenticated Laravel session, NEVER client input.
-- SECURITY INVOKER. They are not an authentication boundary for a DB client with arbitrary DML.
CREATE FUNCTION complete_review(p_review bigint,p_actor bigint,p_outcome text,p_note text) RETURNS bigint
LANGUAGE plpgsql SET search_path TO recruitment,pg_catalog AS $$
DECLARE r application_reviews%ROWTYPE; a applications%ROWTYPE; v vacancies%ROWTYPE; m application_reviews%ROWTYPE; n bigint;
BEGIN
 SELECT * INTO STRICT r FROM application_reviews WHERE id=p_review;
 SELECT * INTO STRICT v FROM vacancies WHERE id=r.vacancy_id FOR UPDATE;
 SELECT * INTO STRICT a FROM applications WHERE id=r.application_id FOR UPDATE;
 SELECT * INTO STRICT r FROM application_reviews WHERE id=p_review FOR UPDATE;
 IF r.assignee_id<>p_actor OR NOT has_staff_scope(p_actor,r.stage,r.org_unit_id) OR NOT EXISTS(
 SELECT 1 FROM staff_assignments WHERE id=r.staff_assignment_id AND valid_from<=CURRENT_TIMESTAMP AND (valid_to IS NULL OR CURRENT_TIMESTAMP<valid_to))
 THEN RAISE EXCEPTION 'reviewer authorization denied' USING ERRCODE='42501'; END IF;
 IF r.status<>'pending' OR r.based_on_submission_id<>a.current_submission_id OR p_note IS NULL OR length(btrim(p_note))=0
 THEN RAISE EXCEPTION 'invalid review state' USING ERRCODE='23514'; END IF;
 IF r.stage='manager' THEN
  IF a.stage<>'manager_review' OR p_outcome IS NULL OR p_outcome NOT IN ('recommended','not_recommended') THEN RAISE EXCEPTION 'invalid manager transition' USING ERRCODE='23514'; END IF;
  IF NOT EXISTS(SELECT 1 FROM application_reviews WHERE application_id=a.id AND stage='sm' AND status='blocked' AND assignee_id<>r.assignee_id AND based_on_submission_id=r.based_on_submission_id)
  THEN RAISE EXCEPTION 'distinct SM on same submission required' USING ERRCODE='23514'; END IF;
  UPDATE application_reviews SET status='completed',outcome=p_outcome,note_internal=p_note,acted_at=clock_timestamp() WHERE id=r.id;
  UPDATE application_reviews SET status='pending' WHERE application_id=a.id AND stage='sm' AND status='blocked';
  UPDATE applications SET stage='sm_review',updated_at=clock_timestamp() WHERE id=a.id;
 ELSE
  SELECT * INTO m FROM application_reviews WHERE application_id=a.id AND stage='manager' AND status='completed';
  IF a.stage<>'sm_review' OR m.id IS NULL OR m.assignee_id=r.assignee_id OR m.based_on_submission_id<>r.based_on_submission_id
   OR p_outcome IS NULL OR p_outcome NOT IN ('accepted','rejected') THEN RAISE EXCEPTION 'Manager before SM required' USING ERRCODE='23514'; END IF;
  IF p_outcome='accepted' THEN
   SELECT count(*) INTO n FROM application_reviews WHERE vacancy_id=v.id AND stage='sm' AND status='completed' AND outcome='accepted';
   IF n>=v.quota THEN RAISE EXCEPTION 'quota exhausted' USING ERRCODE='23514'; END IF;
  END IF;
  UPDATE application_reviews SET status='completed',outcome=p_outcome,note_internal=p_note,acted_at=clock_timestamp() WHERE id=r.id;
  UPDATE applications SET stage='decided',updated_at=clock_timestamp() WHERE id=a.id;
 END IF;
 INSERT INTO application_events(application_id,actor_id,event_type) VALUES(a.id,p_actor,'review.completed');
 RETURN r.id;
END $$;
CREATE FUNCTION publish_decision(p_application bigint,p_actor bigint,p_message text) RETURNS bigint
LANGUAGE plpgsql SET search_path TO recruitment,pg_catalog AS $$
DECLARE a applications%ROWTYPE; rid bigint; result bigint;
BEGIN
 SELECT * INTO STRICT a FROM applications WHERE id=p_application;
 PERFORM 1 FROM vacancies WHERE id=a.vacancy_id FOR UPDATE;
 SELECT * INTO STRICT a FROM applications WHERE id=p_application FOR UPDATE;
 IF NOT has_staff_scope(p_actor,'admin',NULL) THEN RAISE EXCEPTION 'admin required' USING ERRCODE='42501'; END IF;
 SELECT id INTO result FROM application_publications WHERE application_id=a.id;
 IF result IS NOT NULL THEN RETURN result; END IF;
 IF a.stage<>'decided' THEN RAISE EXCEPTION 'not decided' USING ERRCODE='23514'; END IF;
 SELECT id INTO STRICT rid FROM application_reviews WHERE application_id=a.id AND stage='sm' AND status='completed';
 INSERT INTO application_publications(application_id,final_review_id,published_by,public_message) VALUES(a.id,rid,p_actor,coalesce(p_message,'')) RETURNING id INTO result;
 INSERT INTO outbox_events(event_key,event_type,payload) VALUES('decision-published:'||result,'decision.published',jsonb_build_object('publication_id',result));
 INSERT INTO application_events(application_id,actor_id,event_type) VALUES(a.id,p_actor,'decision.published');
 RETURN result;
END $$;
CREATE FUNCTION withdraw_application(p_application bigint,p_actor bigint) RETURNS bigint
LANGUAGE plpgsql SET search_path TO recruitment,pg_catalog AS $$
DECLARE a applications%ROWTYPE;
BEGIN
 SELECT * INTO STRICT a FROM applications WHERE id=p_application;
 PERFORM 1 FROM vacancies WHERE id=a.vacancy_id FOR UPDATE;
 SELECT * INTO STRICT a FROM applications WHERE id=p_application FOR UPDATE;
 IF a.applicant_user_id<>p_actor THEN RAISE EXCEPTION 'owner required' USING ERRCODE='42501'; END IF;
 IF a.stage='withdrawn' THEN RETURN a.id; END IF;
 IF a.stage IN ('draft','decided') THEN RAISE EXCEPTION 'cannot withdraw' USING ERRCODE='23514'; END IF;
 UPDATE application_reviews SET status='cancelled' WHERE application_id=a.id AND status IN ('blocked','pending');
 UPDATE application_revision_requests SET status='cancelled',cancelled_at=clock_timestamp() WHERE application_id=a.id AND status='open';
 UPDATE applications SET stage='withdrawn',withdrawn_at=clock_timestamp(),updated_at=clock_timestamp() WHERE id=a.id;
 INSERT INTO application_events(application_id,actor_id,event_type) VALUES(a.id,p_actor,'application.withdrawn');
 RETURN a.id;
END $$;
CREATE FUNCTION change_quota(p_vacancy bigint,p_actor bigint,p_quota integer) RETURNS void
LANGUAGE plpgsql SET search_path TO recruitment,pg_catalog AS $$
DECLARE v vacancies%ROWTYPE; cap integer; allocated bigint; accepted bigint;
BEGIN
 SELECT * INTO STRICT v FROM vacancies WHERE id=p_vacancy;
 SELECT requested_count INTO STRICT cap FROM internship_requests WHERE id=v.request_id FOR UPDATE;
 SELECT * INTO STRICT v FROM vacancies WHERE id=p_vacancy FOR UPDATE;
 IF NOT has_staff_scope(p_actor,'admin',NULL) THEN RAISE EXCEPTION 'admin required' USING ERRCODE='42501'; END IF;
 SELECT coalesce(sum(quota),0) INTO allocated FROM vacancies WHERE request_id=v.request_id AND id<>v.id;
 SELECT count(*) INTO accepted FROM application_reviews WHERE vacancy_id=v.id AND stage='sm' AND status='completed' AND outcome='accepted';
 IF p_quota IS NULL OR p_quota<=0 OR p_quota<accepted OR allocated+p_quota>cap THEN RAISE EXCEPTION 'quota allocation invalid' USING ERRCODE='23514'; END IF;
 UPDATE vacancies SET quota=p_quota WHERE id=v.id;
 INSERT INTO audit_events(resource_type,resource_id,actor_id,event_type,metadata) VALUES('vacancy',v.id,p_actor,'quota.changed',jsonb_build_object('old',v.quota,'new',p_quota));
END $$;

-- No public API access by default. Dedicated backend role/grants are a deployment task.
REVOKE ALL ON SCHEMA recruitment FROM PUBLIC;
REVOKE ALL ON ALL TABLES IN SCHEMA recruitment FROM PUBLIC;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA recruitment FROM PUBLIC;
COMMIT;
